### ISSUE TITLE
question

### ISSUE THREAD

**Issue by arnauldb** [maniackcrudelis/archivist#4]
Bonjour,

deux petites questions : 

1)-quand je backup, par exemple nextcloud, avec ynh_app_backup=nexcloud, cela backup l'application+fichiers que j'ai mis ds nexcloud+la config de mon nextcloud ? 
Ou faut-il rajouter des dossiers à sauvegarder avec "# Backup of files and directories"

2) 
-J'ai aussi ces messages d'erreur :  

>  Make a real backup for nextcloud_backup
> Warning: Data dir will not be saved, because backup_core_only is set

et

>  Make a temporary backup for bozon_backup
> Warning: Data dir will not be saved, because backup_core_only is set to true.

Que dois-je changer ?

Merci pour toute aide...

**Comment by maniackcrudelis** [comment]
Salut arnauldb

Lorsque tu utilises `ynh_app_backup`, un backup de l'app sera fait à l'aide du script de backup YunoHost.
Donc cela dépend du script, mais habituellement l'ensemble de l'app est sauvegardée, avec sa config et ses données.

Toutefois, certaines app connues pour avoir beaucoup de données disposent d'une option, nommée `backup_core_only`, pour ne pas sauvegarder les données et ne pas surcharger les archives.
Toutefois, dans ton cas, il semblerais que l'option soit restée active.
En général il s'agit d'une entrée `backup_core_only` dans le fichier settings.yml de l'app.
Tu dois pouvoir les supprimer avec cette commande:
```
sudo yunhost app setting -d nextcloud backup_core_only
sudo yunhost app setting -d bozon backup_core_only
```

**Comment by tomdereub** [comment]
Autre question : pour le paramètre max_size, si je comprends bien, il va essayer de limiter les fichiers de sauvegarde à cette limite, mais si un dossier est trop gros il le backup quand même ? Et du coup, pour une même app, il va faire plusieurs archives de sauvegarde, c'est ça ?

**Comment by maniackcrudelis** [comment]
This parameter is a soft limit for a maximum size of a directory.
If it's possible to limit the size by dividing the directories, it'll do it. If it's not, it'll just keep a big directory as it is.
For an app, if it's about the directory of an app itself, it's going to be the same way. If it's a YunoHost backup of an app, it's not a directory but one file. This parameter will do nothing about it.

**Comment by tomdereub** [comment]
Ok thanks. Another question: how does the backups work exactly? Does it backup whole apps each time? Or just changes?
I've about 300Go on Nextcloud, does it backup the whole data each time? I set it 2 days ago on an external HD and it seems to be copying all time since then.

**Comment by maniackcrudelis** [comment]
Archivist is using `yunohost backup app` when it's about to upgrade apps.
So, either you set the variable BACKUP_CORE_ONLY as an environment variable with the `ynh_app_pre_backup` and `ynh_app_post_backup` command. I never tried that though...
Either you avoid to backup nextcloud with `ynh_app_backup` but you use `file_to_backup=` instead.

The best solution would be to have an option for `ynh_app_backup` to add the variable `BACKUP_CORE_ONLY` during the backup. And use `file_to_backup=` for your data.
But it has to be implemented...

And to answer to your 'real' question ;)
Yes, it backups all your data each time, because `yunohost backup app` creates a new backup each time.
It will be different with `file_to_backup=`, which is splitting the directories (as explained earlier) and then check if there's a difference since the last backup.

**Comment by tomdereub** [comment]
Ok, thanks for the answer. For the moment I'll continue to use this : https://forum.yunohost.org/t/how-to-backup-automatically-with-borg-on-a-local-harddrive-without-encryption/4005
It's very efficient to backup my whole server, incuding nextcloud data.
